version: '3.7'

services:
  cf-tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --protocol http2 --no-autoupdate run
    network_mode: "host" 
    environment:
      - TUNNEL_TOKEN=$CF_TUNNEL_TOKEN